### ISSUE TITLE
[BUG] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by dexforint** [algoSupport/nft-downloader#1]
Beginning download of "lazy-lions" collection.

Traceback (most recent call last):
  File "d:\Documents\Downloads\nft-downloader-master\opensea.py", line 102, in <module>
    data = json.loads(requests.get(f"https://api.opensea.io/api/v1/assets?order_direction=asc&offset={offset}&limit=50&collection={CollectionName}&format=json", headers=headers).content.decode())
  File "C:\Users\dexfo\anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\dexfo\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\dexfo\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by algoSupport** [comment]
I have updated the repository. Try again with the latest committed data.
